### ISSUE TITLE
Replay's reset method needs deeper integration with stopping existing animations

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/layersnap#18]
the [reset method](https://github.com/filamentgroup/layersnap/blob/master/src/layersnap.js#L346 ) resets opacity but does not halt existing snap svg iterations in progress. Ideally, we should look into whether that's possible.

Related discussion: https://twitter.com/gnarc/status/981917701693149184

**Comment by ganar** [comment]
What would you advise me in the meantime: Is there a fix I can Apply to the current code? maybe way to destroy the animation at once and `init()` again? it really does jump around.

**Comment by scottjehl** [comment]
@ganar hmm. Well, we're a bit involved in a client project at the moment so I haven't been able to dig into this yet but... At a glance, I think this fix will involve some sort of flag to stop the [delay](https://github.com/filamentgroup/layersnap/blob/master/src/layersnap.js#L82) method from continuing its recursive calls to keep checking if the time has come to start a Snap animation for a given group. For that, we could probably have a property of each layersnap instance that iterates with each animation run. `Reset` could set and iterate that property's value. The `delay` method could check to make sure the current run number lines up with the run number it was passed when it first was called (and if not, just return instead of calling itself again). Additionally, `reset` should probably call [Snap SVG's`stop` method](http://snapsvg.io/docs/#Element.stop) on each animated group, to stop animations currently being iterated by Snap. Those combined will likely cover the full reset you're looking for, since it would stop both layersnap's delay timers for future animations, as well as those currently in animation with snap. I hope to take a look this week.

**Comment by ganar** [comment]
This worked out great! there are some minor issues regarding the persistence of rollovers, but other than that just peachy.
